name: webproj
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip>=19.0
  - flask>=1.0
  - flask-restplus>=0.13
  - flask-cors>=3.0
  - proj-datumgrid-europe>=1.3
  - pyproj>=2.0
